config/routes.rb
Asian::Application.routes.draw do
  get "product/index"

  get "product/show"

  devise_for :admin_users, ActiveAdmin::Devise.config
  root :to => 'home#dashboard'
  ActiveAdmin.routes(self)

  resources :orders

  match 'dashboard' => 'home#dashboard', :as => :dashboard
  match 'contact_us' => 'home#contact_us', :as => :contact_us
  match 'services' => 'home#services', :as => :services
  match 'products' => 'home#products', :as => :products
  match 'partners' => 'home#partners', :as => :partners
  match 'company' => 'home#company', :as => :company

  resources :home do
    member do
    end
    collection do
    end
  end

  

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/order.rb
class Order < ActiveRecord::Base
  attr_accessible :customer_address, :customer_email, :customer_fname, :customer_lname, :customer_phone, :delivered_at, :ordered_at, :product_id, :status
  validates :customer_fname, 
                  :presence => {:message => 'First name cannot be blank'}
  validates :customer_lname, 
                  :presence => {:message => 'Last name cannot be blank'}
  validates :customer_address, 
                  :presence => {:message => 'Address cannot be blank'}
  validates :customer_email, 
                  :presence => {:message => 'Email cannot be blank'}
  validates :customer_phone, 
                  :presence => {:message => 'Phone cannot be blank'}
  validates :product_id, 
                  :presence => {:message => 'Product cannot be blank'}
  validates_format_of :customer_phone, 
                   :with => /\A[0-9]{10}\Z/
  validates_format_of :customer_email, 
                  :with => /^([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})$/i
  validates_format_of :customer_fname,
                  :with => /^[^0-9`!@#\$%\^&*+_=]+$/
  validates_format_of :customer_lname,
                  :with => /^[^0-9`!@#\$%\^&*+_=]+$/

end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :available, :name, :pid, :price, :quality
  
  def self.available_products
    Product.where("available=?", true)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def dashboard
  end
  
  def contact_us
  end
  
  def services
  end
  
  def products
  end
  
  def partners
  end
  
  def company
  end
  
  def thanks
  end
  
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  layout "application"
  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @orders }
    end
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
    @order = Order.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @order }
    end
  end

  # GET /orders/new
  # GET /orders/new.json
  def new
    @order = Order.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @order }
    end
  end

  # GET /orders/1/edit
  def edit
    @order = Order.find(params[:id])
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(params[:order])
    @order.status = "Pending"
    @order.ordered_at = Time.now
    
    respond_to do |format|
      if @order.save
        OrderNotifications.get_order(@order).deliver
        format.html { redirect_to @order, notice: 'Order was successfully Submitted. Our team will contact you shortly. Thanks' }
        format.json { render json: @order, status: :created, location: @order }
      else
        format.html { render action: "new" }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /orders/1
  # PUT /orders/1.json
  def update
    @order = Order.find(params[:id])

    respond_to do |format|
      if @order.update_attributes(params[:order])
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order = Order.find(params[:id])
    @order.destroy

    respond_to do |format|
      format.html { redirect_to orders_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/product_controller.rb
class ProductController < ApplicationController
  def index
    @products = Product.available_products
  end

  def show
    @product = Product.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/views/home/company.html.erb
<div id="templatemo_content_wrapper">
  <p class="em_text">Coming soon</p>
</div>

app/views/home/contact_us.html.erb
<div id="templatemo_content_wrapper">
  <div class="row-fluid">
    <div class="span6">
      <div class="contact-us-details">
        <p class="em_text">Asian Fibro Plast</p>
        <p>Add : Sainath complex, CAT road Rau, Indore, India</p>
        <p>Pin : 453331</p>
        <p>Contact : +919926736374</p>
        <p>Email : asianfibroplast@gmail.com</p>
      </div>
    </div>
    <div class="span6">
      <div class="contact_us_img">
        <%= link_to image_tag("conact_us.jpeg") %>
      </div>
    </div>
  </div>
  <div class="google-map">
    <div id="map-canvas" style="width:800px; height:300px"></div>
  </div>
</div>

<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false"></script>
<script>
  function initialize() {
    $('#map-canvas').attr("style", "width: 940px !important; height: 300px; position: relative; background-color: rgb(229, 227, 223); overflow: hidden;");
    var myLatlng = new google.maps.LatLng(22.636599,75.815493);
    var mapOptions = {
      zoom: 10,
      center: myLatlng,
      mapTypeId: google.maps.MapTypeId.ROADMAP
    }
    var map = new google.maps.Map(document.getElementById('map-canvas'), mapOptions);

    var marker = new google.maps.Marker({
        position: myLatlng,
        map: map,
        title: 'Rau, Indore, India'
    });
  }

  google.maps.event.addDomListener(window, 'load', initialize);
</script>

app/views/home/dashboard.html.erb
<div id="templatemo_content_wrapper">
  <div id="templatemo_content">
    <div id="templatemo_side_column">
      <div class="header_01">Updates</div>
      <div class="side_column_content">
        <div class="news_section">
          <div class="news_date">OCT 22, 2048</div>
          <div class="news_title">Nam auctor aliquam leo</div>
          <p>Aliquam erat volutpat. Etiam blandit, dui non faucibus tincidunt, risus odio fringilla sem, sed urna velit. <a href="#">Read more</a></p>
        </div>

        <div class="news_section">
            <div class="news_date">OCT 19, 2048</div>
            <div class="news_title">In sed lorem vitae arcu </div>
            <p>Curabitur ut mattis urna. Maecenas adipiscing, massa at pharetra fringilla, nibh erat dignissim nisl, vitae pellentesque leo lorem non purus. <a href="#">Read more</a></p>
        </div>
                    
        <div class="news_section">
            <div class="news_date">OCT 16, 2048</div>
            <div class="news_title">Vivamus at odio et tortor</div>
            <p>Etiam ut metus vitae neque rhoncus tristique. Integer sit amet tortor vel diam ornare  ut vitae tellus. <a href="#">Read more</a></p>
        </div>
                    
       <div class="button_01"><a href="#">Read All</a></div>
    </div>
    <div class="margin_bottom_40"></div>
    <div class="header_01">Online booking</div>
    <div class="side_column_content">
      <%= link_to "Click here to book online", new_order_path %>
    </div>
  </div>

  <div id="templatemo_main_content_column">
    <div class="header_01">Welcome to Asian Fibro Plast</div>
      <div class="section_w600">
        <a class='fancybox' href="/assets/catelog.jpg" title="All Product View"><%= image_tag("catelog.jpg", :class=>"fl_image", :size => "200x130") %></a>
        <p class="em_text">Asian Fibro Plast providing services and products which are useful for Housing projects, Bungalows & Villas, Hospitals, Lodges.</p>
        <p class="em_text">Reports educational institutes, Hotels, Industrial Buildings dairy, Pharmaceuticals and Bio Tech Industries.</p>
        <div class="cleaner"></div>
      </div>
      <div class="margin_bottom_30"></div>
      <div class="section_w280 fl margin_right_40">
        <div class="header_01">Services</div>
        <div class="section_w280_content">
          <p>Services that we provide by our products to you.</p>
          <ul class="content_list_01">
            <li>Fire Resistance.</li>
            <li>Sound Proofness.</li>
            <li>Smoke Tightness.</li>
            <li>Burglar Proofness.</li>
          </ul>
          <div class="margin_bottom_20"></div>
          <div class="button_01"><a href="#">Read All</a></div>
        </div>
      </div>
      <div class="section_w280 fl">
        <div class="header_01">Featured Work</div>                  
        <div class="section_w280_content">
          <p>We are providing our services with good features.</p>
          <ul class="content_list_01">
            <li>Good Strength, Weather Proof, Termite Proof, Long Lasting.</li>
            <li>Permanent Colors.</li>
            <li>100% Waterproof Fire Resistant.</li>
            <li>Strong Grip with Hinges, Wood substitute Products.</li>
          </ul>
      </div>
      </div>
      <div class="cleaner"></div>
    </div>
    <div class="cleaner"></div>
  </div>
</div>

app/views/home/partners.html.erb
<div id="templatemo_content_wrapper">
  <p class="em_text">Coming soon</p>
</div>

app/views/home/products.html.erb
<h3> Our Products: </h3>

<div id="templatemo_content_wrapper">
  <% (1..28).each do |i| %>
    <%= link_to image_tag("contact_icon.jpg", :class=>"product-image", :title => "View Details") %>
  <% end %>
</div>

app/views/home/services.html.erb
<div id="templatemo_content_wrapper">
  <p class="em_text"> 	
The Professional Team of the company is capable of handling, as well as carrying everything necessary to provide immediate on-site furniture disassembling,  assembling and all repairs,  on wood, leather, vinyl, fabric, upholstery, antiques, metal, stone, and mechanisms. Methods and products are chosen to make their repairs permanent, invisible and to return furniture to its original or even better condition. On-site or in-shop services offered to all: Manufactures, Stores, Vendors, Warehouses, Designers, Hotels, Restaurants, Construction, Moving, Insurance Companies as well as Individual Customers. We have been at the forefront of the Antique and Modern Repair & Restoration.</p>
</div>

app/views/layouts/_footer.html.erb
<div id="templatemo_footer">
    Copyright @ 2013 <a href="#">Asian Fibro Plast</a>
</div>

app/views/layouts/_header.html.erb
<div id="templatemo_top_panel">
  <div id="site_logo">
    <%= link_to image_tag("comapny_logo.jpg") %>
  </div>
  <div id="header_menu_section">
    <div class="header_menu home_menu">
      <a href="/dashboard"></a>
    </div>
    <div class="header_menu contact_menu">
      <a href="/contact_us"></a>
    </div>
  </div> 
  <div class="cleaner"></div>
</div>
    
<div id="templatemo_menu_banner_panel">
  <div id="templatemo_menu_wrapper">
    <div id="templatemo_menu">
      <ul>
        <li><a href="/dashboard" class="current">Homepage</a></li>
        <li><a href="/services">Services</a></li>
        <li><%= link_to "Products", product_index_path %></a></li>
        <li><a href="/orders/new">Purchase</a></li>
        <li><a href="/company">Our Company</a></li>
        <li class="last"><a href="/contact_us">Contact Us</a></li>
      </ul>    	
    </div>     
  </div>
    
  <div id="templatemo_banner">
    <div class="header_02">Doors for ever, Enjoy exclusive range of frp doors</div>
      <p>Asian Fibro Plast providing services and products which are useful for housing projects, bungalows & villas, Hospitals, Lodges, Reports educational institutes, Hotels, Industrial Buildings dairy, Pharmaceuticals and Bio Tech Industries.</p>
    </div> <!-- end of banner -->
  <div class="cleaner">&nbsp;</div>    
</div> <!-- end of menu & banner panel -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="google-site-verification" content="asianfibroplast" />
  <title>AsianFibroPlast</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="templateo_container">
  <%= render :partial => 'layouts/header' %>
  <%= yield %>
  <%= render :partial => 'layouts/footer' %>
</div>

</body>
</html>

app/views/order_notifications/get_order.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta content="text/html; charset=UTF-8" http-equiv="Content-Type" />
  </head>
  <body>
    <h4>Hi Mohsin,</h4>
    
    <p>
      An order has been came from one of our customer.<br>
      Please find below details :<br>
    </p>
    <p>
      <b>
        Customer First Name : <%= @order.customer_fname %><br>
        Customer Last Name : <%= @order.customer_lname %><br>
        Customer Email : <%= @order.customer_email %><br>
        Customer Address : <%= @order.customer_address %><br>
        Customer Contact Number : <%= @order.customer_phone %><br>
        Ordered Product : <%= @order.product_id %><br>
      </b>
    </p><br>
    Thanks,<br>
    Kapil Patidar
  </body>
</html>

app/views/orders/_form.html.erb
<div id="templatemo_content_wrapper">
  <div class="row-fluid">
    <div class="span6">
      <%= simple_form_for @order, :validate => true do |f| %>
        <%= f.error_notification %>

        <div class="form-inputs">
          <%= f.input :customer_fname, :label=>false, :placeholder => "Enter First Name" %>
          <%= f.input :customer_lname, :label=>false, :placeholder => "Enter Second Name" %>
          <%= f.input :customer_email, :label=>false, :placeholder => "Enter Email" %>
          <%= f.input :customer_address, :label=>false, :placeholder => "Enter Address", as: :string %>
          <%= f.input :customer_phone, :label=>false, :placeholder => "Enter Phone Number" %>
          <%= f.input :product_id, :label=>false, collection: Product.available_products.map { |p| [p.name] }, include_blank: false, :prompt =>"Select product" %>
          <%= f.button :submit, :value=>'Order Now', :class=>"btn btn-primary" %>
        </div>
      <% end %>
    </div>
    <div class="span3">
      <a href="#myModal" data-toggle="modal">View Available Products</a>
    </div>
  </div>
</div>

app/views/orders/edit.html.erb
<div id="templatemo_content_wrapper">
  <h3>You are not authorise for this</h3>
</div>

app/views/orders/index.html.erb
<div id="templatemo_content_wrapper">
  <%= link_to 'New Order', new_order_path %>
</div>

app/views/orders/new.html.erb
<h3>New order</h3>
<%= render 'form' %>

<!-- Modal -->
<div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Available Products</h3>
  </div>
  <div class="modal-body">
    <% Product.available_products.each do |product| %>
      <div class="row-fluid">
        <div class="span3">
          <%= link_to image_tag("contact_icon.jpg", :class=>"product-image", :title => "View Details") %>
        </div>
        <div class="span6">
          <div class="products-details">
            <p>Name : <%= product.name %></p>
            <p>Price : <%= product.price %>rs</p>
            <p>Quality : <%= product.quality %></p>
          </div>
        </div>
        <div class="span3">
          <div class="products-add">
            <a class="add-order btn btn-success" data-product-id="<%= product.name %>">Order This</a>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
  </div>
</div>

<script type="text/javascript">
  $('.add-order').on('click', function() {
    var productid = $(this).data("product-id");
    $('#order_product_id').val(productid)
    $('#myModal .close').click();
  });
</script>

app/views/orders/show.html.erb
<div id="templatemo_content_wrapper">
  <div class="thanks-message">
    <p id="notice"><%= notice %></p>
  </div>
</div>

app/views/product/index.html.erb
<h3> Our Products: </h3>

<div id="templatemo_content_wrapper">
  <% @products.each do |product| %>
    <div class="row-fluid">
      <div class="span3">
        <%= link_to image_tag("contact_icon.jpg", :class=>"product-image", :title => "View Details") %>
      </div>
      <div class="span6">
        <div style="margin-top:20px;">
          <p>Name : <%= product.name %></p>
          <p>Price : <%= product.price %>rs</p>
          <p>Quality : <%= product.quality %></p>
        </div>
      </div>
      <div class="span3">
        <div class="products-add">
          <%= link_to "View Details", product_show_path(:id => product.id), :class => "add-order btn btn-success"%>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/product/show.html.erb
<h3> <%= @product.name %>: </h3>

<div id="templatemo_content_wrapper">
  <div class="row-fluid">
    <div class="span2">
      <%= image_tag("contact_icon.jpg", :class=>"product-image") %>
    </div>
    <div class="span6">
      <div style="margin-top:20px;">
        <p>Name : <%= @product.name %></p>
        <p>Price : <%= @product.price %>rs</p>
        <p>Quality : <%= @product.quality %></p>
      </div>
    </div>
  </div>
</div>